export const GET_TASKS_REQUEST = "GET_TASKS_REQUEST";
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const GET_TASKS_FAILURE = "GET_TASKS_FAILURE";

export const UPDATE_TASKS_REQUEST = "UPDATE_TASKS_REQUEST";
export const UPDATE_TASKS_SUCCESS = "UPDATE_TASKS_SUCCESS";
export const UPDATE_TASKS_FAILURE = "UPDATE_TASKS_FAILURE";

export const ADD_SUBTASK_REQUEST = "ADD_SUBTASK_REQUEST";
export const ADD_SUBTASK_SUCCUSS = "ADD_SUBTASK_SUCCUSS";
export const ADD_SUBTASK_FAILURE = "ADD_SUBTASK_FAILURE";

export const DELETE_SUBTASK_REQUEST = "DELETE_SUBTASK_REQUEST";
export const DELETE_SUBTASK_SUCCUSS = "DELETE_SUBTASK_SUCCUSS";
export const DELETE_SUBTASK_FAILURE = "DELETE_SUBTASK_FAILURE";
